### ISSUE TITLE
Multi tabbed interface

### ISSUE THREAD

**Issue by icewolfz** [icewolfz/jiMUD#85]
Allow connection to multiple times using a tabbed interface to use once client instance for multiple connections to reduce memory and use resource sharing.

Major issue is need some type of window manager to track which open windows (mapper or immortal tools) belong to what mud instance

# Blocking issues

- Randomly leaves application hanging when closed, unable to catch it in debugger, will keep trying to find the cause before 1.0.0 official release **note** i have not seen this reappear in a while, maybe adding all the error checking and safety checks fixed the issue but will continue to watch and see, if it does no appear after a week or so will consider it no longer blocking
- Profile manger seems to randomly freeze when saving, not sure what causes it, my current guess is maybe a race conditions that is causing a loop with the close/client update **note** same as above i have tested many ways and been unable to repeat

# TODO

- [x] Tabs
  - [x] Icon/color to indicate dev or main connection
  - [x] Icon/color to indicate connection status
  - [x] Context menus
    - [x] Tab
      - [x] New connection
      - [x] New window
      - [x] Close
      - [x] Close all but this
      - [ ] Move to new window
      - [ ] Move to start/end
    - [x] Empty space to right of tabs
      - [x] New connection
      - [x] New window
      - [ ] Reload closed tab - maybe allow a setting to save tabs, this will eat memory and require custom close logic as you have to override all close logic and tracking systems and disconnect it and store client as well as window connections to reattach
  - [x] Add new connection button to the right of tabs
  - [x] Drag and drop support
  - [x] Window break out
  - [x] Setting to control if shown if only one tab - see global preferences below
- [x] Menus - Ensure all menu items work and effect current active client
  - [x] Replace system window menu items with custom to allow close of current client and not just close the entire window
  - [x] Close all but active client
  - [x] Save layout
  - [x] Restore layout
  - [x] Window list - list of all open client windows and maybe child windows, this will need thinking as its a dynamic menu and electron does not support dynamic menus easy, moving to the menubar object helps as it allows rebuilding of the menu in the background with seamless replacement but it can add extra overhead
  - [x] Move to a global menubar object for all menu manipulation in 1 place to
- [x] Window tracking - Track all windows needed to restore current view
  - [x] Child window tracking - Track any child windows and states needed to restore view per client
  - [x] Reset states for per client and all
- [x] Global settings - A global settings file for global only settings
  - [x] Show if only one tab - setting to show tab strip even if only one client in window
  - [x] Background throttling - move to global due to how it is linked to all windows
  - [x] Spell checking - global only as can not access per client setting data and can only set spell checking on window creation in most places
  - [x] Check for update - move all dialogs global
  - [x] Fix hidden windows - as all window manipulation should be global
  - [x] Show in task bar - global as you can change per window, but a window could have multiple clients so better to just have 1 setting for all client windows
  - [x] Hide on minimize - same issues as show in taskbar
  - [x] Show in tray - again same issues as others
  - [x] Tray click - linked to show in tray
  - [x] Tray double click - linked to show tray
  - [x] Theme - keep things less confusing just support 1 theme for all windows and in future theme tabstrip
- [x] New settings
  - [x] Create a new interface sub page and move all related interface settings
    - [x] Theme - move from general
    - [x] Always show tabs - move from general
    - [x] Setting to set a layout to load on start
    - [x] Lock layout - when layout saved load old layout and only keep global state 
    - [x] Show add new button - move from general
  - [x] Code Editor Persistent - replace the global editor with a per client setting
  - [x] Show Code Editor - replace the with a per client setting
  - [x] Add a askCloseAll that close all connected clients and not ask for each one
  - [x] Option to run only one instance of application excluding code editing in only mode
  - [x] Option when one instance to create new connection or new window
changes and window positions while keeping first loaded windows and clients, maybe a toggle menu item
- [x] Code editor - figure out how to handle editor only settings vs client settings with out a lot of extra code
- [x] Character manager
  - [x]  Move to sqlite database
  - [x] Add new client
  - [x] Add new window
  - [x] Live editing
    - [ ] A backup tacking system
  - [x] Ability to edit preferences for each character from manager
  - [x] Auto load system - removed as layouts offer better flexibity
- [x] IPC calls - all ipc events will need to track which window they are called from, when a client is created need to set the unique id and pass that as an argument to all ipc calls to know which window is making the call to know what child window to access
- [ ] Code clean up - in general a total cleanup as many will be replaced with new systems or better design
- [ ] Reduce JQuery usage when possible and use native javascript code for both better performance and less memory
- [x] When using inter window systems, any events attacked to objects in other windows need to be unhooked to ensure memory is freed, eg hooking client GMCP event for mapper, would need to remove the hook when closed
- [x] Convert all child windows to use window.open and remove any IPC related calls
  - [x] Mapper
  - [x] Log viewer
  - [x] Chat
  - [x] Code editor
  - [x] Advanced editor
  - [x] Command history
  - [x] Immortal tools
  - [x] Skills
  - [x] Who (if not using open in external)
  - [x] SM Help (if not using open in external)
  - [x] jiMUD help
  - [x] Profile manager
- [x] Replace any old IPC calls with as much inter window hooks/events instead for clearer code and easier linkage between client and windows they opened
- [x] Tray - re-add tray support
  - [x] Remove the old single only items with a window list based on the # of open windows, if only 1 window show the current show/hide/etc.., else show a Windows and  submit of all windows open with show/hide/manager/profiles/etc.. for each window
  - [x] Help linked to current active client/window
  - [x] Preferences - show as global unless only 1 window then do global/client based on setting file
  - [x] Window list - use code/circle icon for current window status like tabs
- [x] Command line arguments
  - [x] --new-connection/nc=[character id|name] create a new connection in current instant/first instant based on setting, this really only should work if using one instant only setting
  - [x] --new-window/nw=[character id|name] create a new window in current instant/first instant based on setting, this really only should work if using one instant only setting
  - [x] --character/c=[character id|name] create new connection after current layout is loaded
  - [x] --layout/l=[file] load layout file instead of default, will override default when exited
  - [x] --ignore-layout/il ignore loading layout and do not save layout on quit
  - [x] --no-layout-save/nls do not save layout on exit
  - [x] --no-character-import/nci do not import characters.json on load
- [x] Global short cuts
  - [x] Ctrl+tab - move to next tab
  - [x] Ctrl+shift+tab - move to previous tab
  - [x] Ctrl+w - close tab/client
- [x] Jump list
  - [x] New connection - create a new connection in current instane when one instant is enabled else create a new instance
  - [x] New window - create a new window in current instance when only one enabled else new window
- [ ] Replace datatables/list with custom built data grid as more control and looks/offers features closer to what wanted
  - [x] Character manger - replace simple list with data grid
  - [ ] Immortal tools - local, remote, and queue list
- [ ] Add a compose mail dialog
- [x] Commands to allow inter client communication, basically to version of all text commands and commands to create/close clients
  - [x] #ALL - send command to all windows
  - [x] #TAB - create new tab connection
  - [x] #WINDOW new/name - expand window to focus/create new connection windows
  - [x] #NAME - set client name
  - [x] #ID - display client id
  - [x] #CLOSE - close window/client
  - [x] #TO - send command to name/id
- [x] Mapper
  - [x] Replace the right detail panel with property grid from code editor
  - [x] Make right detail panel resizable
- [ ] Profile manager
  - [ ] Reduce jquery reliance
  - [ ] Switch to a non bootstrap tree view or find a newer one in prep for updating to bootstrap 5 some day as the bootstrap tree view control is very complex, may need to code my own
  - [ ] Add a live version to allow directly editing of in memory loaded profiles
  - [ ] Add variable branch, maybe leave his to a 1.1.0 or something as variables will require a redesign after 1.0.0 over haul

**Comment by icewolfz** [comment]
this requires #129 to be completed first or there will be a lot of memory or performance issues, as using #129 will allow a single display control and just switch the data back end thus less memory or cpu required

**Comment by icewolfz** [comment]
This is probably unfeasible with out a redesign of the system or some way to use worker threads as if all done in 1 window it would cause bottle necks, a possible fix is using iframe, webview, or maybe browserview to seprate each mud client instance to have each own process

**Comment by icewolfz** [comment]
This may be possible using electron's [Browser-view](https://www.electronjs.org/docs/latest/api/browser-view) which allows to basically allow multiple views with each one their own process, but will require a redesign of the entire code base and how multi windows are done, to begin with will have to store each view in the main process and "switch" based on selected index, and also use window.open for all child windows and track which view they are assigned with either by index or a unique naming system, may start a new branch and play with this idea as it should reduce resources and make it easier to manage multiple connections

**Comment by icewolfz** [comment]
[Browser-view](https://www.electronjs.org/docs/latest/api/browser-view) works, i was able to create a quick dirty multi interface using them and multiple clients in 1 window, so it works now it just a matter of redesigining the entire code flow to work with true multi window systems instead of single, all child windows will need to be redone ot use window.open and linked o the browser view and track unique id but it will create a multi interface with less resources maybe even allow poping out the view into a new window

**Comment by icewolfz** [comment]
Going to be working on a multi tabbed interface with docking/undocking of window support as browser view makes it possible to do a near true system, i could even do a side by side but thats far more complex and would require even more work maybe down the line once i get just a basic tab system working what needs to be done for a multi user jimud:
- [ ] menu state tracking - this is a little harder as some items are "global" while others are tab, may need to track per view and update state based on "switch" or just store menu per view and set it as switched, but does add extra mem use
- [ ] menu actions - all actions need to be updated to effect the current selected view, in theory just need to use the window passed to the menu click event as needed
- [ ] window tracking - this is pretty easy just a simple object of views with a unique id
- [ ] child window tracking - this is sorta already done but only for windows opened by window.open, mapper, chat, editor, etc.. all use separate custom window tracking so that would have to be re-coded to use window.open or change the custom tracking to link them to the view instead of global variables
- [ ] global settings - will require a global settings for all core stuff, and also per character
- [ ] character manager - will need to add option to open new tab or current tab
- [ ] IPC calls - all ipc events will need to track which window they are called from, when a client is created need to set the uniqud id and pass that as an argument to all ipc calls to know which window is making the call to know what child window to access
- [ ] main code clean up - in general a total cleanup of the main.js as a lot of code will need to be redone or generalized or moved to client window if client only
- [ ] convert character manger to sqlite to reduce memory and expand options
- [ ] anything else i can think of at the time

**Comment by icewolfz** [comment]
A basic [experiential tab branch](../tree/tabs) has been created, it will create multiple connection with a basic button bar to switch between clients, and the option to pull out a tab as a new window, all child windows are broken, mapper, etc.. will not work all of that as noted above requires a redesign to correctly link the child windows to the correct client tab/window as needed

**Comment by icewolfz** [comment]
the [experimential tab branch](../tree/tabs) has progressed a lot, fully working tabs, with full drag and drop support in and out of the window, now it just needs more glue code between clients and the window to update tabs/window as needed as well as menu, and to rebuild all the gutted code
